---
- name: Demonstrate operating on MAAS Static Routes
  hosts: all
  gather_facts: false
  module_defaults:
    maas_static_routes:
      username: "{{ maas_username }}"
      password: "{{ maas_password }}"
      site: "{{ maas_site }}"
  tasks:
    - name: Add a static route
      maas_static_routes:
        static_routes: "{{ static_routes }}"
      delegate_to: localhost
      vars:
        static_routes:
          - source: 10.66.0.0/16
            destination: 192.168.66.0/24
            gateway_ip: 10.66.0.1
