---
- name: Demonstrate operating on MAAS tags
  hosts: all
  gather_facts: false
  module_defaults:
    maas_tags:
      username: "{{ maas_username }}"
      password: "{{ maas_password }}"
      site: "{{ maas_site }}"
  tasks:
    - name: Add some tags
      maas_tags:
        tags: "{{ maas_tags }}"
      delegate_to: localhost
      vars:
        maas_tags:
          - name: first_tag
          - name: virtual
    - name: Modify a tag
      maas_tags:
        tags: "{{ maas_tags }}"
      delegate_to: localhost
      vars:
        maas_tags:
          - name: first_tag
            comment: This is the first tag
    - name: Remove a tag
      maas_tags:
        tags: "{{ maas_tags }}"
        state: absent
      delegate_to: localhost
      vars:
        maas_tags:
          - name: first_tag
    - name: Exact List
      maas_tags:
        tags: "{{ maas_tags }}"
        state: exact
      delegate_to: localhost
      vars:
        maas_tags:
          - name: first_tag
          - name: virtual
    - name: Exact List with changes
      maas_tags:
        tags: "{{ maas_tags }}"
        state: exact
      delegate_to: localhost
      vars:
        maas_tags:
          - name: virtual
    - name: Exact List with no members
      maas_tags:
        tags: "{{ maas_tags }}"
        state: exact
      delegate_to: localhost
      vars:
        maas_tags: []
