---
- name: Demonstrate operating on MAAS VLANs
  hosts: all
  gather_facts: false
  module_defaults:
    maas_vlan:
      username: "{{ maas_username }}"
      password: "{{ maas_password }}"
      site: "{{ maas_site }}"
  tasks:
    - name: Add two VLANS
      maas_vlan:
        vlans: "{{ vlans }}"
      delegate_to: localhost
      vars:
        vlans:
          - name: First VLAN 100
            vid: 100
          - name: 200

    - name: Remove one
      maas_vlan:
        vlans: "{{ vlans }}"
        state: absent
      delegate_to: localhost
      vars:
        vlans:
          - name: 200

    - name: Try and add two with the same VID
      maas_vlan:
        vlans: "{{ vlans }}"
      ignore_errors: true
      delegate_to: localhost
      vars:
        vlans:
          - name: 100
          - name: Another VLAN
            vid: 100

    - name: Try and use a parameter we don't support
      maas_vlan:
        vlans: "{{ vlans }}"
      ignore_errors: true
      delegate_to: localhost
      vars:
        vlans:
          - name: 300
            fabric_id: 2

    - name: Try and use an incorrect password
      maas_vlan:
        password: "{{ maas_password }}+"
        vlans: "{{ vlans }}"
      ignore_errors: true
      delegate_to: localhost
      vars:
        vlans:
          - name: 300
