---
dc1:
  children:
    dc1_npe:
    dc1_prod:

dc1_npe:
  children:
    dc1_npe_pod_1:

dc1_npe_pod_1:
  hosts:
    maas1.internal.lotaris.org:

dc1_prod:
  children:
    dc1_prod_pod_1:

dc1_prod_pod_1:
  hosts:
    maas2.internal.lotaris.org:
